apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x54uupgyq-python 
  janus-idp.io/tekton: x54uupgyq-python
  backstage.io/kubernetes-id: x54uupgyq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x54uupgyq-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  